project_name: "Facet"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
definition_of_done: ["Regression tests were created for new behaviors", "Documentation has been created/modified/removed as needed.", "Documentation changes were approved by the docs-architect (8/10 score required)", "Test changes were approved by a test gap analysis review", "Changes to integration points are covered by tests", "All tests pass successfully", "Automatic formatting was applied.", "Linters report no WARNINGS or ERRORS", "The project builds successfully"]
date_format: yyyy-mm-dd
max_column_width: 20
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: false
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 30
task_prefix: "task"
